require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'BraceletMonitoring' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'BraceletMonitoringTests' do
    inherit! :search_paths
    # Pods for testing
  end
  use_native_modules!
end

target 'BraceletMonitoring-tvOS' do
  # Pods for BraceletMonitoring-tvOS

  target 'BraceletMonitoring-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
